"""Action Agent: performs operations with side effects on external systems.

The agent exposes action metadata and risk information; the application runtime
decides whether execution pauses for intervention.
"""

from __future__ import annotations

from app.agent_types.builtin._helpers import (
    ACTIONS,
    BOOLEAN,
    CAPABILITIES,
    DATA,
    DEPLOYMENT,
    EVALUATION,
    HIGHER_IS_BETTER,
    JSON,
    LOWER_IS_BETTER,
    MILLISECONDS,
    MULTI_SELECT,
    NUMBER,
    PERCENTAGE,
    PERFORMANCE,
    QUALITY,
    RELIABILITY,
    SAFETY,
    SAFETY_CATEGORY,
    SELECT,
    TASK_SUCCESS,
    TEXTAREA,
    WORKFLOW,
    metric,
    param,
    when,
)
from app.agent_types.schemas import AgentTypeDefinition

# Parameters the runtime relies on to make intervention decisions for risky work.
HIGH_RISK_METADATA_KEYS = (
    "action_risk_classification",
    "required_permissions",
    "reversibility",
    "external_systems",
    "result_verification",
)

PARAMETERS = [
    param(
        "action_catalog",
        "Allowed actions",
        MULTI_SELECT,
        ACTIONS,
        required=True,
        choices=[
            ("create_record", "Create record"),
            ("update_record", "Update record"),
            ("delete_record", "Delete record"),
            ("send_message", "Send message"),
            ("issue_refund", "Issue refund"),
            ("run_job", "Run job"),
            ("modify_infrastructure", "Modify infrastructure"),
            ("execute_transaction", "Execute transaction"),
        ],
        description="Concrete operations this agent may perform.",
    ),
    param(
        "action_categories",
        "Action categories",
        MULTI_SELECT,
        ACTIONS,
        required=True,
        choices=[
            ("read_write", "Read / write"),
            ("financial", "Financial"),
            ("communication", "Communication"),
            ("infrastructure", "Infrastructure"),
            ("identity", "Identity and access"),
            ("data_lifecycle", "Data lifecycle"),
        ],
    ),
    param(
        "action_risk_classification",
        "Action risk classification",
        SELECT,
        SAFETY,
        required=True,
        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
        default="medium",
        description="Risk exposed to the runtime for every action this agent performs.",
    ),
    param(
        "required_permissions",
        "Required permissions",
        MULTI_SELECT,
        SAFETY,
        required=True,
        choices=[
            ("read", "Read"),
            ("write", "Write"),
            ("delete", "Delete"),
            ("admin", "Admin"),
            ("billing", "Billing"),
            ("infrastructure", "Infrastructure"),
        ],
    ),
    param(
        "runtime_confirmation_requirement",
        "Confirmation required from calling runtime",
        SELECT,
        SAFETY,
        required=True,
        choices=[
            ("never", "Never"),
            ("high_risk_only", "High-risk actions only"),
            ("always", "Always"),
        ],
        default="high_risk_only",
        description=(
            "Metadata the runtime reads before executing. The agent never defines what "
            "the runtime does with it."
        ),
    ),
    param(
        "reversibility",
        "Reversibility",
        SELECT,
        SAFETY,
        required=True,
        choices=[
            ("reversible", "Reversible"),
            ("partially_reversible", "Partially reversible"),
            ("irreversible", "Irreversible"),
        ],
        default="reversible",
    ),
    param("rollback_supported", "Rollback support", BOOLEAN, SAFETY, required=True, default=False),
    param(
        "rollback_procedure",
        "Rollback procedure",
        TEXTAREA,
        SAFETY,
        required=True,
        max_length=4000,
        visible_when=when("rollback_supported", "truthy"),
    ),
    param(
        "idempotency_behavior",
        "Idempotency behavior",
        SELECT,
        ACTIONS,
        required=True,
        choices=[
            ("not_idempotent", "Not idempotent"),
            ("idempotency_key", "Idempotency key"),
            ("natural_idempotent", "Naturally idempotent"),
        ],
        default="idempotency_key",
    ),
    param(
        "transaction_limits",
        "Transaction limits",
        JSON,
        SAFETY,
        required=True,
        description="Per-action ceilings, e.g. max amount, max records, max frequency.",
    ),
    param(
        "retry_safety",
        "Retry safety",
        SELECT,
        WORKFLOW,
        required=True,
        choices=[
            ("safe_to_retry", "Safe to retry"),
            ("retry_with_key", "Retry with idempotency key"),
            ("never_retry", "Never retry"),
        ],
        default="retry_with_key",
    ),
    param(
        "audit_requirements",
        "Audit requirements",
        MULTI_SELECT,
        DEPLOYMENT,
        required=True,
        choices=[
            ("action_log", "Action log"),
            ("payload_capture", "Payload capture"),
            ("actor_attribution", "Actor attribution"),
            ("immutable_trail", "Immutable trail"),
        ],
        default=["action_log", "actor_attribution"],
    ),
    param(
        "external_systems",
        "External systems used",
        MULTI_SELECT,
        DATA,
        required=True,
        choices=[
            ("internal_api", "Internal API"),
            ("crm", "CRM"),
            ("payments", "Payments"),
            ("email", "Email"),
            ("database", "Database"),
            ("cloud_provider", "Cloud provider"),
            ("ticketing", "Ticketing"),
        ],
    ),
    param("dry_run_supported", "Dry-run support", BOOLEAN, CAPABILITIES, required=True, default=True),
    param(
        "action_validation_rules",
        "Action validation rules",
        JSON,
        SAFETY,
        required=True,
        description="Preconditions checked before an action is attempted.",
    ),
    param(
        "partial_failure_behavior",
        "Partial failure behavior",
        SELECT,
        WORKFLOW,
        required=True,
        choices=[
            ("abort", "Abort remaining work"),
            ("continue", "Continue remaining work"),
            ("compensate", "Run compensating actions"),
            ("return_control_to_runtime", "Return control to runtime"),
        ],
        default="return_control_to_runtime",
    ),
    param(
        "duplicate_action_prevention",
        "Duplicate action prevention",
        SELECT,
        ACTIONS,
        required=True,
        choices=[
            ("none", "None"),
            ("idempotency_key", "Idempotency key"),
            ("dedup_window", "Deduplication window"),
            ("external_lock", "External lock"),
        ],
        default="idempotency_key",
    ),
    param(
        "dedup_window_seconds",
        "Deduplication window (seconds)",
        NUMBER,
        ACTIONS,
        required=True,
        min=1,
        max=86400,
        default=300,
        visible_when=when("duplicate_action_prevention", "equals", "dedup_window"),
    ),
    param(
        "result_verification",
        "Result verification behavior",
        SELECT,
        EVALUATION,
        required=True,
        choices=[
            ("none", "None"),
            ("read_back", "Read back result"),
            ("checksum", "Checksum comparison"),
            ("downstream_probe", "Downstream probe"),
        ],
        default="read_back",
    ),
]

METRICS = [
    metric("action_success_rate", "Action success rate", TASK_SUCCESS, PERCENTAGE, HIGHER_IS_BETTER, required=True),
    metric("incorrect_action_rate", "Incorrect-action rate", QUALITY, PERCENTAGE, LOWER_IS_BETTER, required=True),
    metric("unauthorized_action_attempt_rate", "Unauthorized-action attempt rate", SAFETY_CATEGORY, PERCENTAGE, LOWER_IS_BETTER, required=True),
    metric("duplicate_action_rate", "Duplicate-action rate", RELIABILITY, PERCENTAGE, LOWER_IS_BETTER),
    metric("rollback_success_rate", "Rollback success rate", RELIABILITY, PERCENTAGE, HIGHER_IS_BETTER),
    metric("external_api_failure_rate", "External API failure rate", RELIABILITY, PERCENTAGE, LOWER_IS_BETTER),
    metric("execution_latency", "Execution latency", PERFORMANCE, MILLISECONDS, LOWER_IS_BETTER),
    metric("partial_failure_rate", "Partial failure rate", RELIABILITY, PERCENTAGE, LOWER_IS_BETTER),
    metric("idempotency_failure_rate", "Idempotency failure rate", RELIABILITY, PERCENTAGE, LOWER_IS_BETTER),
    metric("action_verification_rate", "Action verification rate", QUALITY, PERCENTAGE, HIGHER_IS_BETTER),
]

TYPE = AgentTypeDefinition(
    id="action",
    name="Action Agent",
    slug="action",
    description="Performs operations that modify external systems or produce side effects.",
    use_cases=[
        "Applying a configuration change",
        "Issuing a refund or billing adjustment",
        "Creating and updating records in external systems",
    ],
    capabilities=[
        "Side-effecting tool execution",
        "Action risk metadata exposure",
        "Rollback and verification support",
    ],
    default_autonomy_level=1,
    default_risk_level="high",
    parameter_definitions=PARAMETERS,
    metric_definitions=METRICS,
)
