"""Governance / Safety Agent: policy, safety, privacy, and security enforcement."""

from __future__ import annotations

from app.agent_types.builtin._helpers import (
    BOOLEAN,
    DATA,
    DEPLOYMENT,
    EVALUATION,
    HIGHER_IS_BETTER,
    JSON,
    LOWER_IS_BETTER,
    MILLISECONDS,
    MULTI_SELECT,
    NUMBER,
    PERCENTAGE,
    PERFORMANCE,
    QUALITY,
    SAFETY,
    SAFETY_CATEGORY,
    SELECT,
    metric,
    param,
    when,
)
from app.agent_types.schemas import AgentTypeDefinition

PARAMETERS = [
    param(
        "policy_sets",
        "Policy sets",
        MULTI_SELECT,
        SAFETY,
        required=True,
        choices=[
            ("content_safety", "Content safety"),
            ("privacy", "Privacy"),
            ("security", "Security"),
            ("regulatory", "Regulatory"),
            ("internal_conduct", "Internal conduct"),
            ("data_handling", "Data handling"),
        ],
    ),
    param(
        "enforcement_mode",
        "Enforcement mode",
        SELECT,
        SAFETY,
        required=True,
        choices=[
            ("monitor", "Monitor"),
            ("warn", "Warn"),
            ("block", "Block"),
            ("return_control_to_runtime", "Return control to runtime"),
        ],
        default="warn",
        description=(
            "Returning control to the runtime stops enforcement here; the runtime decides "
            "what happens next."
        ),
    ),
    param(
        "risk_classes",
        "Risk classes",
        MULTI_SELECT,
        SAFETY,
        required=True,
        choices=[
            ("harmful_content", "Harmful content"),
            ("pii_exposure", "PII exposure"),
            ("credential_leak", "Credential leak"),
            ("regulated_advice", "Regulated advice"),
            ("unauthorized_access", "Unauthorized access"),
            ("prompt_injection", "Prompt injection"),
        ],
    ),
    param("block_threshold", "Block threshold", NUMBER, SAFETY, required=True, min=0, max=1, default=0.8),
    param("warning_threshold", "Warning threshold", NUMBER, SAFETY, required=True, min=0, max=1, default=0.5),
    param(
        "sensitive_data_detection",
        "Sensitive-data detection",
        MULTI_SELECT,
        DATA,
        required=True,
        choices=[
            ("disabled", "Disabled"),
            ("pii", "PII"),
            ("phi", "PHI"),
            ("payment_data", "Payment data"),
            ("credentials", "Credentials"),
            ("source_code", "Source code"),
        ],
        default=["pii", "credentials"],
    ),
    param(
        "redaction_rules",
        "Redaction rules",
        JSON,
        DATA,
        required=True,
        description="Declarative match-and-mask rules applied to detected data.",
    ),
    param(
        "prompt_injection_detection",
        "Prompt-injection detection",
        SELECT,
        SAFETY,
        required=True,
        choices=[("disabled", "Disabled"), ("heuristic", "Heuristic"), ("model_based", "Model based"), ("hybrid", "Hybrid")],
        default="heuristic",
    ),
    param(
        "access_control_behavior",
        "Access-control behavior",
        SELECT,
        SAFETY,
        required=True,
        choices=[
            ("passthrough", "Passthrough"),
            ("verify_scope", "Verify scope"),
            ("deny_by_default", "Deny by default"),
        ],
        default="verify_scope",
    ),
    param(
        "jurisdictions",
        "Jurisdiction or region",
        MULTI_SELECT,
        DEPLOYMENT,
        required=True,
        choices=[
            ("global", "Global"),
            ("us", "United States"),
            ("eu", "European Union"),
            ("uk", "United Kingdom"),
            ("ca", "Canada"),
            ("apac", "APAC"),
        ],
        default=["global"],
    ),
    param(
        "audit_retention_days",
        "Audit retention (days)",
        NUMBER,
        DEPLOYMENT,
        required=True,
        min=1,
        max=3650,
        default=365,
    ),
    param(
        "policy_priority",
        "Policy priority",
        SELECT,
        SAFETY,
        required=True,
        choices=[
            ("regulatory_first", "Regulatory first"),
            ("security_first", "Security first"),
            ("privacy_first", "Privacy first"),
            ("custom_order", "Custom order"),
        ],
        default="regulatory_first",
    ),
    param(
        "policy_priority_order",
        "Custom policy order",
        JSON,
        SAFETY,
        required=True,
        visible_when=when("policy_priority", "equals", "custom_order"),
    ),
    param(
        "policy_conflict_resolution",
        "Conflict resolution between policies",
        SELECT,
        SAFETY,
        required=True,
        choices=[
            ("most_restrictive", "Most restrictive wins"),
            ("highest_priority", "Highest priority wins"),
            ("return_control_to_runtime", "Return control to runtime"),
        ],
        default="most_restrictive",
    ),
    param(
        "enforcement_output_schema",
        "Enforcement output schema",
        JSON,
        DATA,
        required=True,
        description="Shape of the verdict record emitted for each check.",
    ),
    param(
        "violation_severity",
        "Violation severity",
        MULTI_SELECT,
        SAFETY,
        required=True,
        choices=[("info", "Info"), ("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
        default=["low", "medium", "high", "critical"],
    ),
    param(
        "failure_stance",
        "Fail-open or fail-closed behavior",
        SELECT,
        SAFETY,
        required=True,
        choices=[("fail_open", "Fail open"), ("fail_closed", "Fail closed")],
        default="fail_closed",
    ),
    param("policy_coverage_reporting", "Report policy coverage", BOOLEAN, EVALUATION, default=True),
]

METRICS = [
    metric("policy_violation_detection_rate", "Policy violation detection rate", SAFETY_CATEGORY, PERCENTAGE, HIGHER_IS_BETTER, required=True),
    metric("false_positive_rate", "False-positive rate", QUALITY, PERCENTAGE, LOWER_IS_BETTER, required=True),
    metric("false_negative_rate", "False-negative rate", QUALITY, PERCENTAGE, LOWER_IS_BETTER, required=True),
    metric("sensitive_data_leakage_rate", "Sensitive-data leakage rate", SAFETY_CATEGORY, PERCENTAGE, LOWER_IS_BETTER, required=True),
    metric("prompt_injection_detection_rate", "Prompt-injection detection rate", SAFETY_CATEGORY, PERCENTAGE, HIGHER_IS_BETTER),
    metric("unauthorized_access_detection_rate", "Unauthorized-access detection rate", SAFETY_CATEGORY, PERCENTAGE, HIGHER_IS_BETTER),
    metric("redaction_accuracy", "Redaction accuracy", QUALITY, PERCENTAGE, HIGHER_IS_BETTER),
    metric("audit_completeness", "Audit completeness", SAFETY_CATEGORY, PERCENTAGE, HIGHER_IS_BETTER),
    metric("enforcement_latency", "Enforcement latency", PERFORMANCE, MILLISECONDS, LOWER_IS_BETTER),
    metric("policy_coverage", "Policy coverage", SAFETY_CATEGORY, PERCENTAGE, HIGHER_IS_BETTER),
]

TYPE = AgentTypeDefinition(
    id="governance",
    name="Governance / Safety Agent",
    slug="governance",
    description=(
        "Evaluates compliance with policies, safety requirements, privacy controls, security "
        "rules, and organizational restrictions."
    ),
    use_cases=[
        "Screening outputs before they reach users",
        "Detecting sensitive data and redacting it",
        "Applying regional regulatory policy",
    ],
    capabilities=[
        "Policy evaluation",
        "Sensitive-data detection and redaction",
        "Enforcement verdict emission",
    ],
    default_autonomy_level=2,
    default_risk_level="high",
    parameter_definitions=PARAMETERS,
    metric_definitions=METRICS,
)
