"""Memory Agent: stores, retrieves, updates, summarizes, and removes memory."""

from __future__ import annotations

from app.agent_types.builtin._helpers import (
    BOOLEAN,
    CAPABILITIES,
    DATA,
    HIGHER_IS_BETTER,
    IDENTITY,
    JSON,
    LOWER_IS_BETTER,
    MILLISECONDS,
    MULTI_SELECT,
    NUMBER,
    PERCENTAGE,
    PERFORMANCE,
    QUALITY,
    RELIABILITY,
    SAFETY,
    SAFETY_CATEGORY,
    SELECT,
    TEXT,
    WORKFLOW,
    metric,
    param,
    when,
)
from app.agent_types.schemas import AgentTypeDefinition

PARAMETERS = [
    param(
        "memory_type",
        "Memory type",
        MULTI_SELECT,
        CAPABILITIES,
        required=True,
        choices=[
            ("episodic", "Episodic"),
            ("semantic", "Semantic"),
            ("procedural", "Procedural"),
            ("working", "Working"),
            ("profile", "Profile"),
        ],
        default=["episodic"],
    ),
    param(
        "memory_scope",
        "Memory scope",
        SELECT,
        CAPABILITIES,
        required=True,
        choices=[
            ("user", "User"),
            ("session", "Session"),
            ("gathering", "Gathering"),
            ("agent", "Agent"),
            ("workspace", "Workspace"),
        ],
        default="session",
    ),
    param(
        "storage_duration",
        "Storage duration",
        SELECT,
        DATA,
        required=True,
        choices=[
            ("session_only", "Session only"),
            ("days_30", "30 days"),
            ("days_90", "90 days"),
            ("year_1", "1 year"),
            ("indefinite", "Indefinite"),
        ],
        default="days_30",
    ),
    param("write_threshold", "Write threshold", NUMBER, CAPABILITIES, required=True, min=0, max=1, default=0.6),
    param("retrieval_threshold", "Retrieval threshold", NUMBER, CAPABILITIES, required=True, min=0, max=1, default=0.7),
    param(
        "expiration_policy",
        "Expiration policy",
        SELECT,
        DATA,
        required=True,
        choices=[("never", "Never"), ("ttl", "Time to live"), ("last_access", "Last access"), ("capacity_based", "Capacity based")],
        default="ttl",
    ),
    param(
        "conflict_resolution_policy",
        "Conflict-resolution policy",
        SELECT,
        DATA,
        required=True,
        choices=[
            ("latest_wins", "Latest wins"),
            ("highest_confidence", "Highest confidence"),
            ("merge", "Merge"),
            ("keep_both", "Keep both"),
            ("return_control_to_runtime", "Return control to runtime"),
        ],
        default="latest_wins",
    ),
    param(
        "sensitivity_filters",
        "Sensitivity filters",
        MULTI_SELECT,
        SAFETY,
        required=True,
        choices=[
            ("none", "None"),
            ("pii", "PII"),
            ("credentials", "Credentials"),
            ("financial", "Financial"),
            ("health", "Health"),
        ],
        default=["pii", "credentials"],
    ),
    param("consent_metadata_supported", "Consent metadata support", BOOLEAN, SAFETY, required=True, default=True),
    param(
        "compression_strategy",
        "Compression strategy",
        SELECT,
        WORKFLOW,
        required=True,
        choices=[("none", "None"), ("summarize", "Summarize"), ("cluster", "Cluster"), ("embed_only", "Embedding only")],
        default="summarize",
    ),
    param("max_stored_memories", "Maximum stored memories", NUMBER, DATA, required=True, min=1, max=1000000, default=5000),
    param(
        "forgetting_policy",
        "Forgetting policy",
        SELECT,
        DATA,
        required=True,
        choices=[("never", "Never"), ("least_recently_used", "Least recently used"), ("lowest_relevance", "Lowest relevance"), ("explicit_only", "Explicit deletion only")],
        default="least_recently_used",
    ),
    param(
        "deduplication_behavior",
        "Deduplication behavior",
        SELECT,
        DATA,
        required=True,
        choices=[("disabled", "Disabled"), ("exact_match", "Exact match"), ("semantic_similarity", "Semantic similarity")],
        default="semantic_similarity",
    ),
    param(
        "memory_ranking_strategy",
        "Memory ranking strategy",
        SELECT,
        CAPABILITIES,
        required=True,
        choices=[("recency", "Recency"), ("relevance", "Relevance"), ("frequency", "Frequency"), ("hybrid", "Hybrid")],
        default="hybrid",
    ),
    param(
        "memory_update_behavior",
        "Memory update behavior",
        SELECT,
        CAPABILITIES,
        required=True,
        choices=[("append_only", "Append only"), ("overwrite", "Overwrite"), ("versioned", "Versioned")],
        default="versioned",
    ),
    param(
        "memory_namespace",
        "Memory namespace",
        TEXT,
        IDENTITY,
        required=True,
        min_length=2,
        max_length=120,
        pattern=r"^[a-z0-9][a-z0-9_\-]*$",
    ),
    param("cross_user_isolation", "Cross-user isolation", BOOLEAN, SAFETY, required=True, default=True),
    param(
        "memory_source_attribution",
        "Memory source attribution",
        MULTI_SELECT,
        DATA,
        required=True,
        choices=[
            ("session_id", "Session id"),
            ("participant_id", "Participant id"),
            ("agent_id", "Agent id"),
            ("tool_call", "Tool call"),
            ("document", "Document"),
        ],
        default=["session_id", "agent_id"],
    ),
    param(
        "retention_overrides",
        "Retention overrides",
        JSON,
        DATA,
        visible_when=when("expiration_policy", "not_equals", "never"),
    ),
]

METRICS = [
    metric("memory_retrieval_precision", "Memory retrieval precision", QUALITY, PERCENTAGE, HIGHER_IS_BETTER, required=True),
    metric("memory_retrieval_relevance", "Memory retrieval relevance", QUALITY, PERCENTAGE, HIGHER_IS_BETTER),
    metric("incorrect_memory_rate", "Incorrect-memory rate", QUALITY, PERCENTAGE, LOWER_IS_BETTER, required=True),
    metric("stale_memory_rate", "Stale-memory rate", RELIABILITY, PERCENTAGE, LOWER_IS_BETTER),
    metric("contradiction_rate", "Contradiction rate", QUALITY, PERCENTAGE, LOWER_IS_BETTER),
    metric("duplicate_memory_rate", "Duplicate-memory rate", RELIABILITY, PERCENTAGE, LOWER_IS_BETTER),
    metric("privacy_violation_rate", "Privacy violation rate", SAFETY_CATEGORY, PERCENTAGE, LOWER_IS_BETTER, required=True),
    metric("retrieval_latency", "Retrieval latency", PERFORMANCE, MILLISECONDS, LOWER_IS_BETTER),
    metric("memory_write_success_rate", "Memory write success rate", RELIABILITY, PERCENTAGE, HIGHER_IS_BETTER),
    metric("memory_deletion_success_rate", "Memory deletion success rate", RELIABILITY, PERCENTAGE, HIGHER_IS_BETTER),
]

TYPE = AgentTypeDefinition(
    id="memory",
    name="Memory Agent",
    slug="memory",
    description="Stores, retrieves, updates, summarizes, and removes memory used by the agent system.",
    use_cases=[
        "Remembering user preferences across sessions",
        "Summarizing long-running workflow state",
        "Serving prior decisions to other agents",
    ],
    capabilities=[
        "Memory write and retrieval",
        "Summarization and deduplication",
        "Scoped, isolated storage",
    ],
    default_autonomy_level=1,
    default_risk_level="high",
    parameter_definitions=PARAMETERS,
    metric_definitions=METRICS,
)
