"""Operational / Observability Agent: monitors execution, cost, and reliability."""

from __future__ import annotations

from app.agent_types.builtin._helpers import (
    AGENT_SELECTOR,
    BOOLEAN,
    CAPABILITIES,
    COST,
    CURRENCY,
    DEPLOYMENT,
    HIGHER_IS_BETTER,
    JSON,
    LOWER_IS_BETTER,
    MILLISECONDS,
    MULTI_SELECT,
    NUMBER,
    PERCENTAGE,
    PERFORMANCE,
    QUALITY,
    RELIABILITY,
    SELECT,
    WORKFLOW,
    metric,
    param,
    when,
)
from app.agent_types.schemas import AgentTypeDefinition

PARAMETERS = [
    param(
        "monitoring_targets",
        "Monitoring targets",
        MULTI_SELECT,
        CAPABILITIES,
        required=True,
        choices=[
            ("agent_runs", "Agent runs"),
            ("tool_calls", "Tool calls"),
            ("model_calls", "Model calls"),
            ("workflows", "Workflows"),
            ("infrastructure", "Infrastructure"),
            ("cost", "Cost"),
            ("queues", "Queues"),
        ],
    ),
    param(
        "monitoring_frequency",
        "Monitoring frequency",
        SELECT,
        WORKFLOW,
        required=True,
        choices=[("real_time", "Real time"), ("per_minute", "Per minute"), ("per_hour", "Hourly"), ("daily", "Daily")],
        default="per_minute",
    ),
    param("trace_sampling_rate", "Trace sampling rate", NUMBER, CAPABILITIES, required=True, min=0, max=1, default=0.2),
    param("alert_thresholds", "Alert thresholds", JSON, DEPLOYMENT, required=True, description="Metric keys mapped to warning and critical values."),
    param(
        "severity_levels",
        "Severity levels",
        MULTI_SELECT,
        DEPLOYMENT,
        required=True,
        choices=[("info", "Info"), ("warning", "Warning"), ("error", "Error"), ("critical", "Critical")],
        default=["warning", "error", "critical"],
    ),
    param("latency_target_ms", "Latency target (ms)", NUMBER, WORKFLOW, required=True, min=1, max=600000, default=3000),
    param("cost_limit", "Cost limits", NUMBER, DEPLOYMENT, required=True, min=0, default=100),
    param("error_budget", "Error budget (%)", NUMBER, DEPLOYMENT, required=True, min=0, max=100, default=1),
    param("fallback_order", "Fallback order", AGENT_SELECTOR, WORKFLOW, required=True, description="Ordered agents used when a monitored agent is unhealthy."),
    param("incident_routing_metadata", "Incident-routing metadata", JSON, DEPLOYMENT, required=True, description="Service, owner team, and tags attached to incidents."),
    param(
        "auto_remediation",
        "Auto-remediation capabilities",
        MULTI_SELECT,
        CAPABILITIES,
        required=True,
        choices=[
            ("none", "None"),
            ("retry", "Retry failed run"),
            ("restart_worker", "Restart worker"),
            ("switch_model", "Switch model"),
            ("disable_tool", "Disable failing tool"),
            ("scale_out", "Scale out"),
        ],
        default=["none"],
    ),
    param("log_retention_days", "Log retention (days)", NUMBER, DEPLOYMENT, required=True, min=1, max=3650, default=30),
    param(
        "metric_aggregation_window",
        "Metric aggregation window",
        SELECT,
        WORKFLOW,
        required=True,
        choices=[("1m", "1 minute"), ("5m", "5 minutes"), ("15m", "15 minutes"), ("1h", "1 hour"), ("1d", "1 day")],
        default="5m",
    ),
    param(
        "anomaly_detection",
        "Anomaly detection settings",
        SELECT,
        CAPABILITIES,
        required=True,
        choices=[("disabled", "Disabled"), ("static_threshold", "Static threshold"), ("moving_average", "Moving average"), ("seasonal", "Seasonal model")],
        default="moving_average",
    ),
    param(
        "anomaly_sensitivity",
        "Anomaly sensitivity",
        NUMBER,
        CAPABILITIES,
        required=True,
        min=0,
        max=1,
        default=0.5,
        visible_when=when("anomaly_detection", "not_equals", "disabled"),
    ),
    param(
        "trace_correlation",
        "Trace correlation behavior",
        SELECT,
        CAPABILITIES,
        required=True,
        choices=[("none", "None"), ("session_id", "By session"), ("workflow_id", "By workflow"), ("request_id", "By request")],
        default="session_id",
    ),
    param(
        "alert_deduplication",
        "Alert deduplication",
        SELECT,
        DEPLOYMENT,
        required=True,
        choices=[("disabled", "Disabled"), ("fingerprint", "Fingerprint"), ("time_window", "Time window")],
        default="fingerprint",
    ),
    param(
        "health_check_behavior",
        "Health-check behavior",
        SELECT,
        WORKFLOW,
        required=True,
        choices=[("passive", "Passive"), ("active_ping", "Active ping"), ("synthetic_run", "Synthetic run")],
        default="passive",
    ),
    param("health_check_interval_seconds", "Health-check interval (seconds)", NUMBER, WORKFLOW, min=5, max=86400, default=60, visible_when=when("health_check_behavior", "not_equals", "passive")),
]

METRICS = [
    metric("availability", "Availability", RELIABILITY, PERCENTAGE, HIGHER_IS_BETTER, required=True),
    metric("p50_latency", "P50 latency", PERFORMANCE, MILLISECONDS, LOWER_IS_BETTER),
    metric("p95_latency", "P95 latency", PERFORMANCE, MILLISECONDS, LOWER_IS_BETTER, required=True),
    metric("p99_latency", "P99 latency", PERFORMANCE, MILLISECONDS, LOWER_IS_BETTER),
    metric("error_rate", "Error rate", RELIABILITY, PERCENTAGE, LOWER_IS_BETTER, required=True),
    metric("tool_failure_rate", "Tool failure rate", RELIABILITY, PERCENTAGE, LOWER_IS_BETTER),
    metric("model_failure_rate", "Model failure rate", RELIABILITY, PERCENTAGE, LOWER_IS_BETTER),
    metric("cost_per_request", "Cost per request", COST, CURRENCY, LOWER_IS_BETTER),
    metric("mean_time_to_detect", "Mean time to detect", PERFORMANCE, MILLISECONDS, LOWER_IS_BETTER),
    metric("mean_time_to_resolve", "Mean time to resolve", PERFORMANCE, MILLISECONDS, LOWER_IS_BETTER),
    metric("alert_precision", "Alert precision", QUALITY, PERCENTAGE, HIGHER_IS_BETTER),
    metric("alert_duplication_rate", "Alert duplication rate", QUALITY, PERCENTAGE, LOWER_IS_BETTER),
    metric("trace_completeness", "Trace completeness", RELIABILITY, PERCENTAGE, HIGHER_IS_BETTER),
]

TYPE = AgentTypeDefinition(
    id="operational",
    name="Operational / Observability Agent",
    slug="operational",
    description=(
        "Monitors agent execution, infrastructure, traces, costs, failures, and performance."
    ),
    use_cases=[
        "Watching latency and error budgets",
        "Detecting cost anomalies",
        "Correlating traces across a workflow",
    ],
    capabilities=[
        "Metric and trace collection",
        "Anomaly detection",
        "Health checks and auto-remediation",
    ],
    default_autonomy_level=2,
    default_risk_level="medium",
    parameter_definitions=PARAMETERS,
    metric_definitions=METRICS,
)
