"""Orchestration Agent: coordinates agents, tools, tasks, and workflows."""

from __future__ import annotations

from app.agent_types.builtin._helpers import (
    AGENT_SELECTOR,
    BOOLEAN,
    COST,
    COUNT,
    CURRENCY,
    HIGHER_IS_BETTER,
    JSON,
    LOWER_IS_BETTER,
    MILLISECONDS,
    NUMBER,
    PERCENTAGE,
    PERFORMANCE,
    QUALITY,
    RATIO,
    RELIABILITY,
    SELECT,
    TASK_SUCCESS,
    TEXTAREA,
    WORKFLOW,
    metric,
    param,
    when,
)
from app.agent_types.schemas import AgentTypeDefinition

PARAMETERS = [
    param(
        "downstream_agents",
        "Available downstream agents",
        AGENT_SELECTOR,
        WORKFLOW,
        required=True,
        description="Agents this orchestrator may route work to.",
    ),
    param(
        "routing_strategy",
        "Routing strategy",
        SELECT,
        WORKFLOW,
        required=True,
        choices=[
            ("rule_based", "Rule based"),
            ("intent_classification", "Intent classification"),
            ("llm_router", "LLM router"),
            ("capability_match", "Capability match"),
            ("round_robin", "Round robin"),
        ],
        default="intent_classification",
    ),
    param(
        "intent_classification_behavior",
        "Intent classification behavior",
        SELECT,
        WORKFLOW,
        required=True,
        choices=[
            ("disabled", "Disabled"),
            ("single_intent", "Single intent"),
            ("multi_intent", "Multi intent"),
            ("hierarchical", "Hierarchical"),
        ],
        default="single_intent",
    ),
    param("planning_enabled", "Planning enabled", BOOLEAN, WORKFLOW, required=True, default=True),
    param(
        "max_planning_depth",
        "Maximum planning depth",
        NUMBER,
        WORKFLOW,
        required=True,
        min=1,
        max=20,
        default=3,
        visible_when=when("planning_enabled", "truthy"),
    ),
    param(
        "execution_strategy",
        "Sequential or parallel execution",
        SELECT,
        WORKFLOW,
        required=True,
        choices=[("sequential", "Sequential"), ("parallel", "Parallel"), ("hybrid", "Hybrid")],
        default="sequential",
    ),
    param(
        "max_parallel_tasks",
        "Maximum parallel tasks",
        NUMBER,
        WORKFLOW,
        required=True,
        min=1,
        max=50,
        default=3,
        visible_when=when("execution_strategy", "not_equals", "sequential"),
    ),
    param(
        "retry_policy",
        "Retry policy",
        SELECT,
        WORKFLOW,
        required=True,
        choices=[
            ("none", "None"),
            ("fixed", "Fixed interval"),
            ("exponential_backoff", "Exponential backoff"),
            ("retry_with_alternate_agent", "Retry with alternate agent"),
        ],
        default="exponential_backoff",
    ),
    param(
        "termination_criteria",
        "Termination criteria",
        TEXTAREA,
        WORKFLOW,
        required=True,
        max_length=2000,
        description="Conditions that end the workflow (goal met, budget exhausted, no progress).",
    ),
    param(
        "routing_confidence_threshold",
        "Routing confidence threshold",
        NUMBER,
        WORKFLOW,
        required=True,
        min=0,
        max=1,
        default=0.6,
    ),
    param(
        "handoff_rules",
        "Handoff rules",
        JSON,
        WORKFLOW,
        required=True,
        description="Declarative map of conditions to target agents.",
    ),
    param(
        "state_persistence",
        "State persistence",
        SELECT,
        WORKFLOW,
        required=True,
        choices=[
            ("none", "None"),
            ("in_memory", "In memory"),
            ("session", "Session"),
            ("durable", "Durable store"),
        ],
        default="session",
    ),
    param(
        "workflow_timeout_seconds",
        "Workflow timeout (seconds)",
        NUMBER,
        WORKFLOW,
        required=True,
        min=1,
        max=86400,
        default=900,
    ),
    param(
        "failure_propagation",
        "Failure propagation behavior",
        SELECT,
        WORKFLOW,
        required=True,
        choices=[
            ("fail_fast", "Fail fast"),
            ("continue_others", "Continue other branches"),
            ("compensate", "Run compensation"),
            ("return_control_to_runtime", "Return control to runtime"),
        ],
        default="return_control_to_runtime",
    ),
    param(
        "result_aggregation_strategy",
        "Result aggregation strategy",
        SELECT,
        WORKFLOW,
        required=True,
        choices=[
            ("concatenate", "Concatenate"),
            ("summarize", "Summarize"),
            ("best_of", "Best of"),
            ("structured_merge", "Structured merge"),
            ("last_writer", "Last writer"),
        ],
        default="summarize",
    ),
    param(
        "circular_dependency_prevention",
        "Circular dependency prevention",
        SELECT,
        WORKFLOW,
        required=True,
        choices=[
            ("visited_set", "Visited-agent set"),
            ("depth_limit", "Depth limit"),
            ("both", "Visited set and depth limit"),
        ],
        default="both",
    ),
    param(
        "max_agent_handoffs",
        "Maximum agent handoffs",
        NUMBER,
        WORKFLOW,
        required=True,
        min=1,
        max=100,
        default=8,
    ),
]

METRICS = [
    metric("routing_accuracy", "Routing accuracy", QUALITY, PERCENTAGE, HIGHER_IS_BETTER, required=True),
    metric("workflow_completion_rate", "Workflow completion rate", TASK_SUCCESS, PERCENTAGE, HIGHER_IS_BETTER, required=True),
    metric("wrong_agent_selection_rate", "Wrong-agent selection rate", QUALITY, PERCENTAGE, LOWER_IS_BETTER),
    metric("unhandled_intent_rate", "Unhandled intent rate", QUALITY, PERCENTAGE, LOWER_IS_BETTER),
    metric("average_agent_handoffs", "Average agent handoffs", PERFORMANCE, COUNT, LOWER_IS_BETTER),
    metric("retry_rate", "Retry rate", RELIABILITY, PERCENTAGE, LOWER_IS_BETTER),
    metric("replanning_rate", "Replanning rate", RELIABILITY, PERCENTAGE, LOWER_IS_BETTER),
    metric("workflow_latency", "Workflow latency", PERFORMANCE, MILLISECONDS, LOWER_IS_BETTER, required=True),
    metric("cost_per_workflow", "Cost per workflow", COST, CURRENCY, LOWER_IS_BETTER),
    metric("tool_call_efficiency", "Tool-call efficiency", PERFORMANCE, RATIO, HIGHER_IS_BETTER),
    metric("termination_accuracy", "Termination accuracy", QUALITY, PERCENTAGE, HIGHER_IS_BETTER),
]

TYPE = AgentTypeDefinition(
    id="orchestration",
    name="Orchestration Agent",
    slug="orchestration",
    description="Coordinates agents, tools, tasks, and workflows.",
    use_cases=[
        "Routing a request to the right specialist agent",
        "Planning and running multi-step workflows",
        "Aggregating results from parallel agent work",
    ],
    capabilities=[
        "Agent routing and handoff",
        "Planning and replanning",
        "Workflow state coordination",
    ],
    default_autonomy_level=3,
    default_risk_level="medium",
    parameter_definitions=PARAMETERS,
    metric_definitions=METRICS,
)
