"""Retrieval / Context Agent: finds, ranks, filters, and prepares information."""

from __future__ import annotations

from app.agent_types.builtin._helpers import (
    BOOLEAN,
    CAPABILITIES,
    DATA,
    DATA_SOURCE_SELECTOR,
    HIGHER_IS_BETTER,
    JSON,
    LOWER_IS_BETTER,
    MILLISECONDS,
    MULTI_SELECT,
    NUMBER,
    PERCENTAGE,
    PERFORMANCE,
    QUALITY,
    RATIO,
    RELIABILITY,
    SAFETY,
    SCORE,
    SELECT,
    WORKFLOW,
    metric,
    param,
    when,
)
from app.agent_types.schemas import AgentTypeDefinition

PARAMETERS = [
    param(
        "search_strategy",
        "Search strategy",
        SELECT,
        CAPABILITIES,
        required=True,
        choices=[
            ("keyword", "Keyword"),
            ("semantic", "Semantic"),
            ("hybrid", "Hybrid"),
            ("graph", "Graph"),
        ],
        default="hybrid",
    ),
    param("search_sources", "Search sources", DATA_SOURCE_SELECTOR, DATA, required=True),
    param("top_k", "Top-K", NUMBER, CAPABILITIES, required=True, min=1, max=200, default=8),
    param("similarity_threshold", "Similarity threshold", NUMBER, CAPABILITIES, required=True, min=0, max=1, default=0.7),
    param(
        "query_expansion",
        "Query expansion",
        SELECT,
        CAPABILITIES,
        required=True,
        choices=[("disabled", "Disabled"), ("synonyms", "Synonyms"), ("llm_rewrite", "LLM rewrite"), ("multi_query", "Multi query")],
        default="disabled",
    ),
    param(
        "reranking",
        "Reranking",
        SELECT,
        CAPABILITIES,
        required=True,
        choices=[("disabled", "Disabled"), ("cross_encoder", "Cross encoder"), ("llm_rerank", "LLM rerank"), ("recency_weighted", "Recency weighted")],
        default="disabled",
    ),
    param("metadata_filters", "Metadata filters", JSON, DATA, required=True, description="Declarative filters applied to candidate documents."),
    param("chunk_size", "Chunk size (tokens)", NUMBER, DATA, required=True, min=32, max=8192, default=512),
    param("chunk_overlap", "Chunk overlap (tokens)", NUMBER, DATA, required=True, min=0, max=2048, default=64),
    param("context_token_budget", "Context token budget", NUMBER, WORKFLOW, required=True, min=128, max=1000000, default=8000),
    param("deduplication_threshold", "Deduplication threshold", NUMBER, DATA, required=True, min=0, max=1, default=0.92),
    param(
        "freshness_requirement",
        "Freshness requirements",
        SELECT,
        DATA,
        required=True,
        choices=[("any", "Any"), ("within_24h", "Within 24 hours"), ("within_7d", "Within 7 days"), ("within_30d", "Within 30 days")],
        default="any",
    ),
    param("source_priority", "Source priority", JSON, DATA, required=True, description="Ordered source weighting used when results tie."),
    param("permission_filtering", "Permission filtering", BOOLEAN, SAFETY, required=True, default=True),
    param(
        "citation_metadata_requirements",
        "Citation metadata requirements",
        MULTI_SELECT,
        DATA,
        required=True,
        choices=[
            ("source_id", "Source id"),
            ("title", "Title"),
            ("url", "URL"),
            ("author", "Author"),
            ("timestamp", "Timestamp"),
            ("chunk_range", "Chunk range"),
        ],
        default=["source_id", "title", "timestamp"],
    ),
    param(
        "context_compression_strategy",
        "Context compression strategy",
        SELECT,
        WORKFLOW,
        required=True,
        choices=[("none", "None"), ("truncate", "Truncate"), ("extractive_summary", "Extractive summary"), ("abstractive_summary", "Abstractive summary")],
        default="none",
    ),
    param("max_source_count", "Maximum source count", NUMBER, DATA, required=True, min=1, max=200, default=10),
    param(
        "empty_result_behavior",
        "Empty result behavior",
        SELECT,
        WORKFLOW,
        required=True,
        choices=[
            ("return_empty", "Return empty context"),
            ("broaden_query", "Broaden query and retry"),
            ("fallback_source", "Use fallback source"),
            ("return_control_to_runtime", "Return control to runtime"),
        ],
        default="broaden_query",
    ),
    param(
        "fallback_source",
        "Fallback source",
        DATA_SOURCE_SELECTOR,
        DATA,
        required=True,
        visible_when=when("empty_result_behavior", "equals", "fallback_source"),
    ),
]

METRICS = [
    metric("retrieval_precision", "Retrieval precision", QUALITY, PERCENTAGE, HIGHER_IS_BETTER, required=True),
    metric("retrieval_recall", "Retrieval recall", QUALITY, PERCENTAGE, HIGHER_IS_BETTER, required=True),
    metric("hit_rate_at_k", "Hit rate at K", QUALITY, PERCENTAGE, HIGHER_IS_BETTER),
    metric("mean_reciprocal_rank", "Mean reciprocal rank", QUALITY, SCORE, HIGHER_IS_BETTER),
    metric("ndcg", "NDCG", QUALITY, SCORE, HIGHER_IS_BETTER),
    metric("context_relevance", "Context relevance", QUALITY, SCORE, HIGHER_IS_BETTER, required=True),
    metric("duplicate_result_rate", "Duplicate-result rate", RELIABILITY, PERCENTAGE, LOWER_IS_BETTER),
    metric("stale_source_rate", "Stale-source rate", RELIABILITY, PERCENTAGE, LOWER_IS_BETTER),
    metric("permission_filter_accuracy", "Permission-filter accuracy", QUALITY, PERCENTAGE, HIGHER_IS_BETTER),
    metric("retrieval_latency", "Retrieval latency", PERFORMANCE, MILLISECONDS, LOWER_IS_BETTER),
    metric("context_compression_ratio", "Context compression ratio", PERFORMANCE, RATIO, HIGHER_IS_BETTER),
]

TYPE = AgentTypeDefinition(
    id="retrieval_context",
    name="Retrieval / Context Agent",
    slug="retrieval-context",
    description="Finds, ranks, filters, and prepares information for downstream agents.",
    use_cases=[
        "Building grounded context for a task agent",
        "Searching internal documentation",
        "Permission-aware knowledge retrieval",
    ],
    capabilities=[
        "Hybrid search and reranking",
        "Permission-aware filtering",
        "Context assembly and compression",
    ],
    default_autonomy_level=1,
    default_risk_level="medium",
    parameter_definitions=PARAMETERS,
    metric_definitions=METRICS,
)
