"""Task / Domain Agent: specialized work inside a task category or business domain."""

from __future__ import annotations

from app.agent_types.builtin._helpers import (
    BOOLEAN,
    CAPABILITIES,
    DATA,
    DATA_SOURCE_SELECTOR,
    EVALUATION,
    HIGHER_IS_BETTER,
    IDENTITY,
    JSON,
    LOWER_IS_BETTER,
    MILLISECONDS,
    MULTI_SELECT,
    NUMBER,
    PERCENTAGE,
    PERFORMANCE,
    QUALITY,
    RELIABILITY,
    SAFETY,
    SCORE,
    SELECT,
    TASK_SUCCESS,
    TEXT,
    TEXTAREA,
    TOOLS,
    WORKFLOW,
    metric,
    param,
    when,
)
from app.agent_types.schemas import AgentTypeDefinition

PARAMETERS = [
    param(
        "domain",
        "Domain",
        TEXT,
        IDENTITY,
        required=True,
        min_length=2,
        max_length=120,
        description="Business or technical domain this agent owns.",
    ),
    param(
        "supported_tasks",
        "Supported tasks",
        MULTI_SELECT,
        CAPABILITIES,
        required=True,
        choices=[
            ("analysis", "Analysis"),
            ("summarization", "Summarization"),
            ("classification", "Classification"),
            ("extraction", "Extraction"),
            ("generation", "Generation"),
            ("diagnosis", "Diagnosis"),
            ("recommendation", "Recommendation"),
            ("transformation", "Transformation"),
        ],
    ),
    param(
        "input_formats",
        "Input formats",
        MULTI_SELECT,
        DATA,
        required=True,
        choices=[
            ("plain_text", "Plain text"),
            ("markdown", "Markdown"),
            ("json", "JSON"),
            ("csv", "CSV"),
            ("sql", "SQL"),
            ("logs", "Logs"),
            ("documents", "Documents"),
        ],
        default=["plain_text"],
    ),
    param(
        "output_format",
        "Output format",
        SELECT,
        DATA,
        required=True,
        choices=[
            ("plain_text", "Plain text"),
            ("markdown", "Markdown"),
            ("json", "JSON"),
            ("table", "Table"),
        ],
        default="markdown",
    ),
    param(
        "structured_output_required",
        "Structured output required",
        BOOLEAN,
        DATA,
        required=True,
        default=False,
    ),
    param(
        "output_schema",
        "Output schema",
        JSON,
        DATA,
        required=True,
        description="JSON schema the agent output must satisfy.",
        visible_when=when("structured_output_required", "truthy"),
    ),
    param(
        "domain_instructions",
        "Domain instructions",
        TEXTAREA,
        IDENTITY,
        required=True,
        min_length=20,
        max_length=8000,
    ),
    param(
        "knowledge_sources",
        "Knowledge sources",
        DATA_SOURCE_SELECTOR,
        DATA,
        required=True,
    ),
    param(
        "required_evidence",
        "Required evidence",
        MULTI_SELECT,
        EVALUATION,
        required=True,
        choices=[
            ("none", "None"),
            ("source_citations", "Source citations"),
            ("tool_output", "Tool output"),
            ("computation_trace", "Computation trace"),
            ("reference_documents", "Reference documents"),
        ],
        default=["source_citations"],
    ),
    param(
        "confidence_threshold",
        "Confidence threshold",
        NUMBER,
        EVALUATION,
        required=True,
        min=0,
        max=1,
        default=0.7,
    ),
    param(
        "data_freshness_requirement",
        "Data freshness requirement",
        SELECT,
        DATA,
        required=True,
        choices=[
            ("any", "Any"),
            ("within_24h", "Within 24 hours"),
            ("within_7d", "Within 7 days"),
            ("within_30d", "Within 30 days"),
            ("real_time", "Real time"),
        ],
        default="any",
    ),
    param(
        "failure_behavior",
        "Failure behavior",
        SELECT,
        WORKFLOW,
        required=True,
        choices=[
            ("fail", "Fail"),
            ("retry", "Retry"),
            ("partial_result", "Return partial result"),
            ("return_control_to_runtime", "Return control to runtime"),
        ],
        default="return_control_to_runtime",
    ),
    param(
        "domain_validation_rules",
        "Domain-specific validation rules",
        JSON,
        SAFETY,
        required=True,
        description="Declarative checks applied to outputs before they leave the agent.",
    ),
    param(
        "unsupported_task_behavior",
        "Unsupported task behavior",
        SELECT,
        SAFETY,
        required=True,
        choices=[
            ("decline", "Decline"),
            ("best_effort", "Best effort with disclaimer"),
            ("return_control_to_runtime", "Return control to runtime"),
        ],
        default="return_control_to_runtime",
    ),
    param(
        "allowed_tool_categories",
        "Allowed tool categories",
        MULTI_SELECT,
        TOOLS,
        required=True,
        choices=[
            ("read_only", "Read only"),
            ("analysis", "Analysis"),
            ("search", "Search"),
            ("computation", "Computation"),
            ("write", "Write"),
        ],
        default=["read_only"],
    ),
]

METRICS = [
    metric("task_accuracy", "Task accuracy", QUALITY, PERCENTAGE, HIGHER_IS_BETTER, required=True),
    metric("domain_correctness", "Domain correctness", QUALITY, PERCENTAGE, HIGHER_IS_BETTER, required=True),
    metric("schema_validity", "Schema validity", RELIABILITY, PERCENTAGE, HIGHER_IS_BETTER),
    metric("citation_coverage", "Citation coverage", QUALITY, PERCENTAGE, HIGHER_IS_BETTER),
    metric("groundedness", "Groundedness", QUALITY, SCORE, HIGHER_IS_BETTER, required=True),
    metric("unsupported_claim_rate", "Unsupported claim rate", QUALITY, PERCENTAGE, LOWER_IS_BETTER),
    metric("task_completion_rate", "Task completion rate", TASK_SUCCESS, PERCENTAGE, HIGHER_IS_BETTER),
    metric("processing_time", "Processing time", PERFORMANCE, MILLISECONDS, LOWER_IS_BETTER),
    metric("output_consistency", "Output consistency", QUALITY, SCORE, HIGHER_IS_BETTER),
    metric("correction_rate", "Correction rate", QUALITY, PERCENTAGE, LOWER_IS_BETTER),
]

TYPE = AgentTypeDefinition(
    id="task_domain",
    name="Task / Domain Agent",
    slug="task-domain",
    description="Performs specialized work within a task category or business domain.",
    use_cases=[
        "Database performance analysis",
        "Contract clause extraction",
        "Domain-specific diagnostics and recommendations",
    ],
    capabilities=[
        "Domain reasoning with instructions",
        "Structured output generation",
        "Evidence-backed answers",
    ],
    default_autonomy_level=2,
    default_risk_level="medium",
    parameter_definitions=PARAMETERS,
    metric_definitions=METRICS,
)
