"""User-Facing Agent: communicates directly with users."""

from __future__ import annotations

from app.agent_types.builtin._helpers import (
    AGENT_SELECTOR,
    BOOLEAN,
    CAPABILITIES,
    COUNT,
    EVALUATION,
    HIGHER_IS_BETTER,
    IDENTITY,
    LOWER_IS_BETTER,
    MILLISECONDS,
    MULTI_SELECT,
    NUMBER,
    PERCENTAGE,
    PERFORMANCE,
    QUALITY,
    RATIO,
    SAFETY,
    SCORE,
    SELECT,
    TASK_SUCCESS,
    TEXT,
    TEXTAREA,
    USER_EXPERIENCE,
    WORKFLOW,
    metric,
    param,
    when,
)
from app.agent_types.schemas import AgentTypeDefinition

PARAMETERS = [
    param(
        "interaction_channels",
        "Interaction channels",
        MULTI_SELECT,
        CAPABILITIES,
        required=True,
        choices=[
            ("in_app_session", "In-app session"),
            ("chat_widget", "Chat widget"),
            ("email", "Email"),
            ("voice", "Voice"),
            ("api", "API"),
            ("slack", "Slack"),
        ],
        description="Where this agent talks to users.",
    ),
    param(
        "supported_user_groups",
        "Supported user groups",
        MULTI_SELECT,
        CAPABILITIES,
        required=True,
        choices=[
            ("internal_staff", "Internal staff"),
            ("customers", "Customers"),
            ("partners", "Partners"),
            ("administrators", "Administrators"),
            ("public", "Public"),
        ],
    ),
    param(
        "conversation_mode",
        "Conversation mode",
        SELECT,
        CAPABILITIES,
        required=True,
        choices=[
            ("single_turn", "Single turn"),
            ("multi_turn", "Multi turn"),
            ("guided_flow", "Guided flow"),
        ],
        default="multi_turn",
    ),
    param(
        "response_formats",
        "Response formats",
        MULTI_SELECT,
        CAPABILITIES,
        required=True,
        choices=[
            ("plain_text", "Plain text"),
            ("markdown", "Markdown"),
            ("structured_json", "Structured JSON"),
            ("table", "Table"),
            ("chart", "Chart"),
        ],
        default=["markdown"],
    ),
    param(
        "personalization_level",
        "Personalization level",
        SELECT,
        CAPABILITIES,
        required=True,
        choices=[
            ("none", "None"),
            ("basic", "Basic"),
            ("profile_aware", "Profile aware"),
            ("history_aware", "History aware"),
        ],
        default="basic",
    ),
    param(
        "session_context_behavior",
        "Session context behavior",
        SELECT,
        WORKFLOW,
        required=True,
        choices=[
            ("no_context", "No context"),
            ("current_session", "Current session only"),
            ("recent_sessions", "Recent sessions"),
            ("full_history", "Full history"),
        ],
        default="current_session",
    ),
    param(
        "supported_languages",
        "Supported languages",
        MULTI_SELECT,
        CAPABILITIES,
        required=True,
        choices=[
            ("en", "English"),
            ("es", "Spanish"),
            ("fr", "French"),
            ("de", "German"),
            ("pt", "Portuguese"),
            ("ja", "Japanese"),
        ],
        default=["en"],
    ),
    param(
        "tone_guidelines",
        "Tone / communication guidelines",
        TEXTAREA,
        IDENTITY,
        required=True,
        max_length=4000,
    ),
    param(
        "citation_requirement",
        "Citation requirements",
        SELECT,
        EVALUATION,
        required=True,
        choices=[
            ("none", "Not required"),
            ("when_available", "When available"),
            ("always", "Always required"),
        ],
        default="when_available",
    ),
    param(
        "feedback_collection",
        "User feedback collection",
        SELECT,
        EVALUATION,
        required=True,
        choices=[
            ("disabled", "Disabled"),
            ("thumbs", "Thumbs up / down"),
            ("rating", "Rating scale"),
            ("free_text", "Free text"),
        ],
        default="thumbs",
    ),
    param("streaming_enabled", "Streaming responses", BOOLEAN, CAPABILITIES, required=True, default=True),
    param(
        "max_response_length",
        "Maximum response length (characters)",
        NUMBER,
        WORKFLOW,
        required=True,
        min=100,
        max=100000,
        default=4000,
    ),
    param(
        "max_response_latency_ms",
        "Maximum response latency target (ms)",
        NUMBER,
        WORKFLOW,
        required=True,
        min=100,
        max=600000,
        default=8000,
    ),
    param(
        "error_message_behavior",
        "Error message behavior",
        SELECT,
        SAFETY,
        required=True,
        choices=[
            ("generic_message", "Generic message"),
            ("detailed_message", "Detailed message"),
            ("return_control_to_runtime", "Return control to runtime"),
        ],
        default="generic_message",
    ),
    param(
        "unsupported_request_behavior",
        "Unsupported request behavior",
        SELECT,
        SAFETY,
        required=True,
        choices=[
            ("decline", "Decline politely"),
            ("suggest_alternative", "Suggest alternative"),
            ("handoff_to_agent", "Hand off to another agent"),
            ("return_control_to_runtime", "Return control to runtime"),
        ],
        default="return_control_to_runtime",
    ),
    param(
        "handoff_target_agent_id",
        "Hand-off target agent",
        AGENT_SELECTOR,
        WORKFLOW,
        required=True,
        visible_when=when("unsupported_request_behavior", "equals", "handoff_to_agent"),
    ),
    param("greeting_message", "Greeting message", TEXT, IDENTITY, max_length=500),
]

METRICS = [
    metric("task_completion_rate", "Task completion rate", TASK_SUCCESS, PERCENTAGE, HIGHER_IS_BETTER, required=True),
    metric("user_satisfaction", "User satisfaction", USER_EXPERIENCE, SCORE, HIGHER_IS_BETTER, required=True),
    metric("first_contact_resolution", "First-contact resolution", TASK_SUCCESS, PERCENTAGE, HIGHER_IS_BETTER),
    metric("average_turns_per_task", "Average turns per task", USER_EXPERIENCE, COUNT, LOWER_IS_BETTER),
    metric("response_latency", "Response latency", PERFORMANCE, MILLISECONDS, LOWER_IS_BETTER, required=True),
    metric("abandonment_rate", "Abandonment rate", USER_EXPERIENCE, PERCENTAGE, LOWER_IS_BETTER),
    metric("hallucination_rate", "Hallucination rate", QUALITY, PERCENTAGE, LOWER_IS_BETTER, required=True),
    metric("citation_accuracy", "Citation accuracy", QUALITY, PERCENTAGE, HIGHER_IS_BETTER),
    metric("response_relevance", "Response relevance", QUALITY, SCORE, HIGHER_IS_BETTER),
    metric("context_retention_accuracy", "Context retention accuracy", QUALITY, RATIO, HIGHER_IS_BETTER),
]

TYPE = AgentTypeDefinition(
    id="user_facing",
    name="User-Facing Agent",
    slug="user-facing",
    description=(
        "Communicates directly with users and presents results produced by the agent system."
    ),
    use_cases=[
        "Support and help desk conversations",
        "Guided onboarding and product walkthroughs",
        "Presenting analysis produced by downstream agents",
    ],
    capabilities=[
        "Conversational interaction",
        "Response formatting and citation",
        "Session context retention",
    ],
    default_autonomy_level=2,
    default_risk_level="medium",
    parameter_definitions=PARAMETERS,
    metric_definitions=METRICS,
)
